name              'nano'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs and configures nano'
version           '3.0.14'
source_url        'https://github.com/sous-chefs/nano'
issues_url        'https://github.com/sous-chefs/nano/issues'
chef_version      '>= 15.3'

supports 'amazon'
supports 'arch'
supports 'centos'
supports 'debian'
supports 'fedora'
supports 'opensuseleap'
supports 'oracle'
supports 'redhat'
supports 'scientific'
supports 'suse'
supports 'ubuntu'
